In [2]:
# Explore the python pgenlib for read pgen files.
# Install and API
# https://github.com/chrchang/plink-ng/blob/master/2.0/Python/python_api.txt

In [12]:
import pgenlib
import numpy as np

In [37]:
pf =  pgenlib.PgenReader(bytes('./test.indels.missing.pgen','utf8'))

In [38]:
N_sample = pf.get_raw_sample_ct()
N_sample

3

In [39]:
buf = np.empty(N_sample, np.int8)

In [40]:
# by default, 0/1/2 represents thealternate allele count.
genos = pf.read(0,buf)

In [41]:
buf

array([0, 1, 2], dtype=int8)

In [42]:
genos = pf.read(3,buf)
buf

array([1, 1, 2], dtype=int8)

In [44]:
# With missing, missing were coded as -9.
genos = pf.read(6,buf)
buf

array([ 1, -9, -9], dtype=int8)

In [45]:
pf.close()

In [47]:
# Only loading a subset of samples.
#  sample_subset is an optional numpy uint32 array of (0-based) indexes in
#    increasing order, telling the reader to only consider the specified samples
#    when loading or counting genotypes.
sample_subset = np.array([0,2],np.uint32)
sample_subset

array([0, 2], dtype=uint32)

In [48]:
pf =  pgenlib.PgenReader(bytes('./test.indels.missing.pgen','utf8'), sample_subset=sample_subset)

In [49]:
N_sample = pf.get_raw_sample_ct()
N_sample

3

In [62]:
buf = np.empty(2, np.int8)
pf.read(6,buf)
buf

array([ 1, -9], dtype=int8)

In [63]:
buf*.03

array([ 0.03, -0.27])

In [57]:
pf.read(3,buf)
buf

array([1, 2], dtype=int8)

In [59]:
import os.path

In [61]:
os.path.isfile('./1.get.plink.file.s')

False